name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for bringing an issue to our attention! To help us even more, make sure to include all relevant information! Thanks :thumbsup:!'
        pr-message: 'Hi! Thanks for contributing back to TypeGC! To help us even more, make sure to follow our contribution guide! Thanks :thumbsup:!'
